name: DocFX

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./repo
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./repo
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
      - run: dotnet tool install --global docfx --version 2.77.0
      - name: Generate docs
        run: |
          docfx ./docs/docfx.json
          mkdir -p ../out
          cp -R ./docs/_site/* ../out
      - name: Unsus docs
        run: |
          find . -type f -exec sed -i 's/AA\xE0\xB6\x9EAA/@/g' {} ';'
          find . -type f -exec sed -i 's/\xE0\xB6\x9E//g' {} ';'
          find . -type f -exec sed -i 's/public interface //g' {} ';'
          find . -type f -exec sed -i 's/public static class //g' {} ';'
          find . -type f -exec sed -i 's/public static //g' {} ';'
          find . -type f -exec sed -i 's/public abstract class //g' {} ';'
          find . -type f -exec sed -i 's/public class //g' {} ';'
          find . -type f -exec sed -i 's/public event //g' {} ';'
          find . -type f -exec sed -i 's/public //g' {} ';'
          find . -type f -exec sed -i 's/ { private get; init; }//g' {} ';'
          find . -type f -exec sed -i 's/ { init; }//g' {} ';'
        working-directory: ./out
      - name: Update gh-pages and push changes
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git clean -xdf
          git checkout gh-pages
          git clean -xdf
          git rm --cached -r .
          cp -R ../out/* .
          git add .
          git commit -m "Update files" && git push || echo "No changes to commit"
